const { defaultLogger } = require('../utils/logger');
class CommandRegistry {
  constructor(manager, multiagent) { this.manager = manager; this.multiagent = multiagent; this.log = defaultLogger.child('commands'); this._commands = new Map(); this._registerBuiltins(); }
  register(cmd) { if (!cmd.name || !cmd.execute) throw new Error('Command needs name+execute'); this._commands.set(cmd.name, cmd); }
  async execute(cmdName, args = {}) { const cmd = this._commands.get(cmdName); if (!cmd) throw new Error(`Unknown: ${cmdName}`); return cmd.execute(this.manager, args, this.multiagent); }
  list() { return Array.from(this._commands.values()).map(c => ({ name: c.name, description: c.description, usage: c.usage })); }
  help(cmdName) { if (cmdName) { const c = this._commands.get(cmdName); return c ? `${c.name} — ${c.description}\nUsage: ${c.usage}` : `Unknown: ${cmdName}`; } return this.list().map(c => `  ${c.name.padEnd(22)} ${c.description}`).join('\n'); }
  _registerBuiltins() {
    this.register({ name: '/agents', description: 'List all agents', usage: '/agents [category]', execute: async (mgr, args) => { const a = mgr.list(args.category ? { category: args.category } : {}); return a.length ? a.map(x => `  ${x.slug.padEnd(26)} ${x.description}`).join('\n') : 'No agents found.'; } });
    this.register({ name: '/list-agents', description: 'List agents with details', usage: '/list-agents [--verbose]', execute: async (mgr, args) => mgr.list().map(a => { let l = `  ${a.slug.padEnd(26)} v${a.version} [${a.category}]`; if (args.verbose) { l += `\n    ${a.description}`; if (a.skills?.length) l += `\n    Skills: ${a.skills.join(', ')}`; } return l; }).join('\n') });
    this.register({ name: '/install-agent', description: 'Install agent from source', usage: '/install-agent <source>', execute: async (mgr, args) => { if (!args.source) return 'Usage: /install-agent <source>'; return `Installed: ${await mgr.install(args.source)}`; } });
    this.register({ name: '/remove-agent', description: 'Remove an agent', usage: '/remove-agent <slug>', execute: async (mgr, args) => { if (!args.slug) return 'Usage: /remove-agent <slug>'; await mgr.remove(args.slug); return `Removed: ${args.slug}`; } });
    this.register({ name: '/update-agent', description: 'Update an agent', usage: '/update-agent <slug>', execute: async (mgr, args) => { if (!args.slug) return 'Usage: /update-agent <slug>'; const u = await mgr.update(args.slug); return `Updated: ${u.slug || args.slug}`; } });
    this.register({ name: '/run-agent', description: 'Run an agent', usage: '/run-agent <slug> [task]', execute: async (mgr, args) => { if (!args.slug) return 'Usage: /run-agent <slug>'; return JSON.stringify(await mgr.run(args.slug, { task: args.task || '' }), null, 2); } });
    this.register({ name: '/search-agent', description: 'Search agents by query', usage: '/search-agent <query>', execute: async (mgr, args) => { if (!args.query) return 'Usage: /search-agent <query>'; const r = mgr.search(args.query); return r.length ? r.map(a => `  ${a.slug.padEnd(26)} ${a.description}`).join('\n') : `No results for: ${args.query}`; } });
    this.register({ name: '/export-agent', description: 'Export agent to file', usage: '/export-agent <slug> [path]', execute: async (mgr, args) => { if (!args.slug) return 'Usage: /export-agent <slug>'; return `Exported: ${await mgr.exportAgent(args.slug, args.path)}`; } });
    this.register({ name: '/import-agent', description: 'Import agent from file', usage: '/import-agent <path>', execute: async (mgr, args) => { if (!args.path) return 'Usage: /import-agent <path>'; return `Imported: ${await mgr.importAgent(args.path)}`; } });
    this.register({ name: '/team-create', description: 'Create agent team', usage: '/team-create <name> <agent1,agent2,...>', execute: async (mgr, args, multi) => { if (!args.name || !args.agents) return 'Usage: /team-create <name> <agents>'; return `Team: ${multi.createTeam(args.name, args.agents.split(',').map(s => s.trim()), { strategy: args.strategy || 'sequential' })}`; } });
    this.register({ name: '/team-execute', description: 'Execute task with team', usage: '/team-execute <team> <task>', execute: async (mgr, args, multi) => { if (!args.team || !args.task) return 'Usage: /team-execute <team> <task>'; return JSON.stringify(await multi.teamExecute(args.team, args.task), null, 2); } });
    this.register({ name: '/team-list', description: 'List all teams', usage: '/team-list', execute: async (mgr, args, multi) => { const t = multi.listTeams(); return t.length ? t.map(x => `  ${x.name.padEnd(20)} ${x.agents.length} agents [${x.strategy}]`).join('\n') : 'No teams found.'; } });
    this.register({ name: '/team-agents', description: 'List multi-agent participants', usage: '/team-agents', execute: async (mgr, args, multi) => { const a = multi.listAgents(); return a.length ? a.map(x => `  ${x.slug.padEnd(26)} role=${x.role} state=${x.state}`).join('\n') : 'No participants found.'; } });
    this.register({ name: '/consensus', description: 'Request team consensus', usage: '/consensus <team> <proposal>', execute: async (mgr, args, multi) => { if (!args.team || !args.proposal) return 'Usage: /consensus <team> <proposal>'; const r = await multi.requestConsensus(args.team, args.proposal); return `Consensus: ${r.approved ? 'APPROVED' : 'REJECTED'} (${r.totalVotes} votes)\n${JSON.stringify(r, null, 2)}`; } });
  }
}
module.exports = { CommandRegistry };
